FORMAT: 1A

# Forrester MSON

API Intro

## Customers Collection [/customers{?country,revenue}]

Customers Collection text

+ Parameters
    + country: USA (optional, string) - country text
    + revenue: 1000 (optional, number) - revenue text

### List All Customers [GET]

GET collection text

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Customer], fixed-type)
        
### Metadata on Customers [HEAD]

HEAD Collection text

+ Response 200

### Customers Methods [OPTIONS]

OPTIONS Collection Text

+ Response 204
    + Headers

            Allow: HEAD,GET,POST,OPTIONS

    
### Create a New Customer [POST]

POST Collection Text

+ Request (application/json; charset=utf-8)
    + Attributes (Customer)

+ Response 201 (application/json; charset=utf-8)
    + Headers

            Location: /customers/42

    + Body
    + Attributes
        + id: 42 (number, required) - Uniquely identifies a Customer
        + Include Customer

## Customer Resource [/customers/{ID}]

Customer Resource text

+ Parameters
    + ID: 42 (required, string) - Unique ID of a customer

### Retrieve a single Customer [GET]

Retrieve a single Customer Text

+ Response 200 (application/json; charset=utf-8)
    + Headers

            Location: /customers/42

    + Body
    + Attributes
        + id: 42 (number, required) - Uniquely identifies a Customer
        + Include Customer

### Modify a single Customer [PUT]

Change a single Customer Text

+ Request (application/json; charset=utf-8)
    + Attributes (Customer)

+ Response 200 (application/json; charset=utf-8)
    + Headers

            Location: /customers/42

    + Body
    + Attributes
        + id: 42 (number, required) - Uniquely identifies a Customer
        + Include Customer
            
### Remove a single Customer [DELETE]

Remove Single Customer Text

+ Response 204
            
### Metadata on single Customer [HEAD]

HEAD Customer text

+ Response 200
    + Headers

            Location: /customers/42

### single Customer Methods [OPTIONS]

OPTIONS Collection Text

+ Response 204
    + Headers
    
            Allow: HEAD,GET,OPTIONS,PUT,DELETE
        
## Orders [/orders{?validateOnly}]

submitOrder Text

+ Parameters
    + validateOnly: yes (optional, string) - validation option text

### Submit a new Order [POST]

Create Order Text

+ Request (application/json; charset=utf-8)
    + Attributes (Order)

+ Response 201 (application/json; charset=utf-8)
    + Headers

            Location: /customers/84

    + Body       
    + Attributes
        + id: 84 (number, required) - Uniquely identifies an accepted Order
        + Include Order

+ Response 400 (application/problem+json; charset=utf-8)
    + Attributes (Problem)

### Orders Methods [OPTIONS]

OPTIONS Collection Text

+ Response 200 (text/plain)
    + Headers

            Allow: POST,OPTIONS
        
# Data Structures

## Customer
+ name: Emmanuel Paraskakis (required) - Full customer name
+ address (Address)
+ phone: `1-800-555-1212` (optional) - Customer contact phone number

## Address
+ street: 100 Oracle Pkwy (required) - Street Address
+ locality: Redwood City (required) - City or other locality name
+ region: CA (optional) - State or region
+ postalCode: 94065 (required) - ZIP in USA
+ country: USA (required) - ISO 3166 alpha-3 country code 

## Order
+ customerID: 42 (required, string) - Valid ID of an existing customer who has placed the Order
+ shippingAddress (Address)
+ header
    + paymentToken: `6e113782-a186-11e8-b659-529269fb1459` (required, string) - Valid Payment token generated by Payments API
    + shippingMethodID: 1 (required, string) - Shipping method selected
+ detail (array[Item], fixed-type)

## Item
+ itemID: 21 (required, string) - Valid ID from the Items API
+ quantity: 1 (required, number) - A positive integer representing the quantity of items needed

## Problem
+ type: `https://example.net/duplicate-payment-token` (required, string) - Valid link for problem reference
+ title: Duplicate Payment Token (required, string) - Human readable short title of problem
+ detail: Payment is associated with a previous order - (optional, string) - Human redable long description of problem